# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities_data = "citydata.csv"
cities_data_df = pd.read_csv(cities_data)
cities_data_df

,City Name,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Acarí,-15.4311,-74.6158,72.73,70,100,3.38,PE,1612662487
1,Jacareacanga,-6.2222,-57.7528,74.35,93,100,2.10,BR,1612662487
2,Dikson,73.5069,80.5464,-27.47,87,90,9.57,RU,1612662238
3,Oni,42.5794,43.4425,38.12,77,100,1.03,GE,1612662487
4,Sattahip,12.6664,100.9007,87.01,78,20,4.61,TH,1612662487
...,...,...,...,...,...,...,...,...,...
555,Çerkezköy,41.2850,28.0003,42.80,100,99,2.30,TR,1612662525
556,Katherine,-14.4667,132.2667,75.20,94,90,6.91,AU,1612662525
557,Great Bend,38.3645,-98.7648,14.00,79,40,9.22,US,1612662525
558,Grand Gaube,-20.0064,57.6608,75.00,86,2,3.00,MU,1612662452
559,Māgām,34.0833,74.5833,26.13,78,0,1.70,IN,1612662525

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Access maps with unique API key
gmaps.configure(api_key=g_key)

In [4]:
locations = cities_data_df[["Latitude", "Longitude"]]
humidity = cities_data_df["Humidity"].astype(float)

#Check the max humidity
max_humidity = humidity.max()
max_humidity

100.0

In [5]:
#Generate gmaps to see the heatmap
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
#Find a good weather for the vacation
good_weather_cities = cities_data_df.loc[(cities_data_df["Cloudiness"] == 0) & (cities_data_df["Max Temp"] >70) & (cities_data_df["Max Temp"] <80) & (cities_data_df["Wind Speed"] < 10),:]

good_weather_cities =good_weather_cities.dropna(how='any')

print(f'Choose one of these {len(good_weather_cities)} cities for your trip!')
good_weather_cities

Choose one of these 17 cities for your trip!

,City Name,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
19,Sakaraha,-22.9000,44.5333,72.57,89,0,3.42,MG,1612662488
53,Granja,-3.1203,-40.8261,76.69,81,0,6.31,BR,1612662207
95,Quatre Cocos,-20.2078,57.7625,75.00,86,0,3.00,MU,1612662396
126,Wanaka,-44.7000,169.1500,77.74,31,0,5.17,NZ,1612662495
137,Fernández,-27.9204,-63.8935,78.01,51,0,5.01,AR,1612662496
156,Iquique,-20.2208,-70.1431,73.40,49,0,9.22,CL,1612662478
181,Tabou,4.4230,-7.3528,78.69,89,0,8.16,CI,1612662499
249,Harper,4.3750,-7.7169,79.02,88,0,8.81,LR,1612662477
260,Jalingo,8.8833,11.3667,73.83,20,0,4.88,NG,1612662504
265,Imbituba,-28.2400,-48.6703,73.40,68,0,3.44,BR,1612662505
303,Cap Malheureux,-19.9842,57.6142,75.00,86,0,3.00,MU,1612662466
325,Santa Cruz de la Sierra,-17.8000,-63.1667,77.00,73,0,5.75,BO,1612662456
329,Chunhuhub,19.5500,-88.6833,76.08,85,0,5.03,MX,1612662509
333,Paka,4.6374,103.4368,79.18,74,0,8.03,MY,1612662509
343,Fuerte Olimpo,-21.0415,-57.8738,70.05,64,0,4.12,PY,1612662510
385,General Roca,-39.0333,-67.5833,78.80,61,0,9.26,AR,1612662488
514,Sompeta,18.9333,84.6000,70.48,52,0,4.41,IN,1612662522

In [7]:
#Remove the 'index' column and name the data into hotel_df 
hotel_df = good_weather_cities.reset_index()
del hotel_df['index']
hotel_df

,City Name,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Sakaraha,-22.9000,44.5333,72.57,89,0,3.42,MG,1612662488
1,Granja,-3.1203,-40.8261,76.69,81,0,6.31,BR,1612662207
2,Quatre Cocos,-20.2078,57.7625,75.00,86,0,3.00,MU,1612662396
3,Wanaka,-44.7000,169.1500,77.74,31,0,5.17,NZ,1612662495
4,Fernández,-27.9204,-63.8935,78.01,51,0,5.01,AR,1612662496
5,Iquique,-20.2208,-70.1431,73.40,49,0,9.22,CL,1612662478
6,Tabou,4.4230,-7.3528,78.69,89,0,8.16,CI,1612662499
7,Harper,4.3750,-7.7169,79.02,88,0,8.81,LR,1612662477
8,Jalingo,8.8833,11.3667,73.83,20,0,4.88,NG,1612662504
9,Imbituba,-28.2400,-48.6703,73.40,68,0,3.44,BR,1612662505
10,Cap Malheureux,-19.9842,57.6142,75.00,86,0,3.00,MU,1612662466
11,Santa Cruz de la Sierra,-17.8000,-63.1667,77.00,73,0,5.75,BO,1612662456
12,Chunhuhub,19.5500,-88.6833,76.08,85,0,5.03,MX,1612662509
13,Paka,4.6374,103.4368,79.18,74,0,8.03,MY,1612662509
14,Fuerte Olimpo,-21.0415,-57.8738,70.05,64,0,4.12,PY,1612662510
15,General Roca,-39.0333,-67.5833,78.80,61,0,9.26,AR,1612662488
16,Sompeta,18.9333,84.6000,70.48,52,0,4.41,IN,1612662522

In [9]:
#Find those places through gmap 
vaca_locations = hotel_df[["Latitude", "Longitude"]]

vaca_humidity = hotel_df["Humidity"].astype(float)

# Plot Heatmap
vaca_fig = gmaps.figure()

# Create heat layer
vaca_heat_layer = gmaps.heatmap_layer(vaca_locations, weights=vaca_humidity, 
                                 dissipating=False, max_intensity=50,
                                 point_radius=2.5)

# Add layer
vaca_fig.add_layer(vaca_heat_layer)

# Display figure
vaca_fig

Figure(layout=FigureLayout(height='420px'))

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
# Hotel variable
hotels = []

# Loop through narrowed down dataframe to get nearest hotel
for city in range(len(hotel_df["City Name"])):

    lat = hotel_df.loc[city]["Latitude"]
    lng = hotel_df.loc[city]["Longitude"]

    city_coords = f"{lat},{lng}"

    params = {
        "location": city_coords, 
        "types": "lodging",
        "radius": 5000,
        "key": g_key
    }

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"   

    hotel_request = requests.get(base_url, params=params)
    hotel_response = hotel_request.json()

    try:
        hotels.append(hotel_response["results"][0]["name"])
    except:
        hotels.append("No Hotels Near You")

# Dataframe with nearest hotel
hotel_df["Nearest Hotel"] = hotels
hotel_df

,City Name,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Nearest Hotel
0,Sakaraha,-22.9000,44.5333,72.57,89,0,3.42,MG,1612662488,Le Relais
1,Granja,-3.1203,-40.8261,76.69,81,0,6.31,BR,1612662207,Pousada Casa Grande
2,Quatre Cocos,-20.2078,57.7625,75.00,86,0,3.00,MU,1612662396,Emeraude Beach Attitude Hotel
3,Wanaka,-44.7000,169.1500,77.74,31,0,5.17,NZ,1612662495,Wanaka Homestead Lodge and Cottages
4,Fernández,-27.9204,-63.8935,78.01,51,0,5.01,AR,1612662496,Cordoba Hunting
5,Iquique,-20.2208,-70.1431,73.40,49,0,9.22,CL,1612662478,Backpacker`s Hostel Iquique
6,Tabou,4.4230,-7.3528,78.69,89,0,8.16,CI,1612662499,hotêl doufoulougou
7,Harper,4.3750,-7.7169,79.02,88,0,8.81,LR,1612662477,Screensaver
8,Jalingo,8.8833,11.3667,73.83,20,0,4.88,NG,1612662504,Debright Motel
9,Imbituba,-28.2400,-48.6703,73.40,68,0,3.44,BR,1612662505,Praia Hotel Imbituba
10,Cap Malheureux,-19.9842,57.6142,75.00,86,0,3.00,MU,1612662466,Pereybere Hotel & Spa
11,Santa Cruz de la Sierra,-17.8000,-63.1667,77.00,73,0,5.75,BO,1612662456,Hotel Cortez
12,Chunhuhub,19.5500,-88.6833,76.08,85,0,5.03,MX,1612662509,No Hotels Near You
13,Paka,4.6374,103.4368,79.18,74,0,8.03,MY,1612662509,Rumbia Resort Villa Paka Terengganu
14,Fuerte Olimpo,-21.0415,-57.8738,70.05,64,0,4.12,PY,1612662510,Hospedaje DAMI
15,General Roca,-39.0333,-67.5833,78.80,61,0,9.26,AR,1612662488,Hotel El Recreo
16,Sompeta,18.9333,84.6000,70.48,52,0,4.41,IN,1612662522,బెంకిలి భైరొడమ్మ క్రికెట్ గ్రౌండ్

In [11]:
# NOTE: Do not change any of the code in this cell
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Nearest Hotel}</dd>
<dt>City</dt><dd>{City Name}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [12]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content= [f"Nearest Hotel: {hotel}" for hotel in hotels])
vaca_fig.add_layer(markers)
# Display figure
vaca_fig

Figure(layout=FigureLayout(height='420px'))